### ISSUE TITLE
Line 1155 in the figure script

### ISSUE THREAD

**Issue by cahartin** [USEPA/FrEDI_NPD#2]
Are we renaming CIL and ATS to Ext Temp? are we grouping them together?

**Comment by emcduffie** [comment]
Yes, renaming ATS to 'Temperature Related Mortality'. The next line is replacing 'CIL' with an empty string so that sectors like 'CIL Agriculture' are just listed as 'Agriculture'. Data for the CIL Ext Temperature sector are removed from the stats files during a separate pre-processing step.
